  version: "3"
  services:
    statki2021:
      build: .
      container_name: statki2021
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/marinas
      ports:
        - 8000:8080
      restart: always
      depends_on:
        - db
    db:
      image: postgres
      container_name: db
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=marinas
        - PGDATA=/var/lib/postgresql/data/pgdata
      ports:
        - 5000:5432
      volumes:
        - pgdata:/var/lib/postgresql/data
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      restart: always
  volumes:
    pgdata: