package pl.prazynski.monitorowaniejednostekmorskich.utils;

import java.util.HashMap;

public class Codes {

    HashMap<String, String> countryMap = new HashMap<>();

    public Codes() {
        countryMap.put( "Andorra","ad");
        countryMap.put( "United Arab Emirates","ae");
        countryMap.put( "Afghanistan","af");
        countryMap.put( "Antigua & Barbuda","ag");
        countryMap.put( "Anguilla","ai");
        countryMap.put( "Albania","al");
        countryMap.put( "Armenia","am");
        countryMap.put( "Angola","ao");
        countryMap.put( "Antarctica","aq");
        countryMap.put( "Argentina","ar");
        countryMap.put( "American Samoa","as");
        countryMap.put( "Austria","at");
        countryMap.put( "Australia","au");
        countryMap.put( "Aruba","aw");
        countryMap.put( "Åland Islands","ax");
        countryMap.put( "Azerbaijan","az");
        countryMap.put( "Bosnia and Herzegovina","ba");
        countryMap.put( "Barbados","bb");
        countryMap.put( "Bangladesh","bd");
        countryMap.put( "Belgium","be");
        countryMap.put( "Burkina Faso","bf");
        countryMap.put( "Bulgaria","bg");
        countryMap.put( "Bahrain","bh");
        countryMap.put( "Burundi","bi");
        countryMap.put( "Benin","bj");
        countryMap.put( "Saint Barthélemy","bl");
        countryMap.put( "Bermuda","bm");
        countryMap.put( "Brunei","bn");
        countryMap.put( "Bolivia","bo");
        countryMap.put( "Caribbean Netherlands","bq");
        countryMap.put( "Brazil","br");
        countryMap.put( "Bahamas","bs");
        countryMap.put( "Bhutan","bt");
        countryMap.put( "Bouvet Island","bv");
        countryMap.put( "Botswana","bw");
        countryMap.put( "Belarus","by");
        countryMap.put( "Belize","bz");
        countryMap.put( "Canada","ca");
        countryMap.put( "Cocos (Keeling) Islands","cc");
        countryMap.put( "DR Congo","cd");
        countryMap.put( "Central African Republic","cf");
        countryMap.put( "Republic of the Congo","cg");
        countryMap.put( "Switzerland","ch");
        countryMap.put( "Côte d'Ivoire (Ivory Coast)","ci");
        countryMap.put( "Cook Islands","ck");
        countryMap.put( "Chile","cl");
        countryMap.put( "Cameroon","cm");
        countryMap.put( "China","cn");
        countryMap.put( "Colombia","co");
        countryMap.put( "Costa Rica","cr");
        countryMap.put( "Cuba","cu");
        countryMap.put( "Cape Verde","cv");
        countryMap.put( "Curaçao","cw");
        countryMap.put( "Christmas Island","cx");
        countryMap.put( "Cyprus","cy");
        countryMap.put( "Czechia","cz");
        countryMap.put( "Germany","de");
        countryMap.put( "Djibouti","dj");
        countryMap.put( "Denmark","dk");
        countryMap.put( "Denmark (Dis)","dk");
        countryMap.put( "Dominica","dm");
        countryMap.put( "Dominican Republic","do");
        countryMap.put( "Algeria","dz");
        countryMap.put( "Ecuador","ec");
        countryMap.put( "Estonia","ee");
        countryMap.put( "Egypt","eg");
        countryMap.put( "Western Sahara","eh");
        countryMap.put( "Eritrea","er");
        countryMap.put( "Spain","es");
        countryMap.put( "Ethiopia","et");
        countryMap.put( "European Union","eu");
        countryMap.put( "Finland","fi");
        countryMap.put( "Fiji","fj");
        countryMap.put( "Falkland Islands","fk");
        countryMap.put( "Micronesia","fm");
        countryMap.put( "Faroe Islands","fo");
        countryMap.put( "Faeroe Islands","fo");
        countryMap.put( "France","fr");
        countryMap.put( "Gabon","ga");
        countryMap.put( "United Kingdom","gb");
        countryMap.put( "England","gb-eng");
        countryMap.put( "Northern Ireland","gb-nir");
        countryMap.put( "Scotland","gb-sct");
        countryMap.put( "Wales","gb-wls");
        countryMap.put( "Grenada","gd");
        countryMap.put( "Georgia","ge");
        countryMap.put( "French Guiana","gf");
        countryMap.put( "Guernsey","gg");
        countryMap.put( "Ghana","gh");
        countryMap.put( "Gibraltar","gi");
        countryMap.put( "Greenland","gl");
        countryMap.put( "Gambia","gm");
        countryMap.put( "Guinea","gn");
        countryMap.put( "Guadeloupe","gp");
        countryMap.put( "Equatorial Guinea","gq");
        countryMap.put( "Greece","gr");
        countryMap.put( "South Georgia","gs");
        countryMap.put( "Guatemala","gt");
        countryMap.put( "Guam","gu");
        countryMap.put( "Guinea-Bissau","gw");
        countryMap.put( "Guyana","gy");
        countryMap.put( "Hong Kong","hk");
        countryMap.put( "Hong kong- China","hk");
        countryMap.put( "Heard Island and McDonald Islands","hm");
        countryMap.put( "Honduras","hn");
        countryMap.put( "Croatia","hr");
        countryMap.put( "Haiti","ht");
        countryMap.put( "Hungary","hu");
        countryMap.put( "Indonesia","id");
        countryMap.put( "Ireland","ie");
        countryMap.put( "Israel","il");
        countryMap.put( "Isle of Man","im");
        countryMap.put( "India","in");
        countryMap.put( "British Indian Ocean Territory","io");
        countryMap.put( "Iraq","iq");
        countryMap.put( "Iran","ir");
        countryMap.put( "Iceland","is");
        countryMap.put( "Italy","it");
        countryMap.put( "Jersey","je");
        countryMap.put( "Jamaica","jm");
        countryMap.put( "Jordan","jo");
        countryMap.put( "Japan","jp");
        countryMap.put( "Kenya","ke");
        countryMap.put( "Kyrgyzstan","kg");
        countryMap.put( "Cambodia","kh");
        countryMap.put( "Kiribati","ki");
        countryMap.put( "Comoros","km");
        countryMap.put( "Saint Kitts and Nevis","kn");
        countryMap.put( "North Korea","kp");
        countryMap.put( "South Korea","kr");
        countryMap.put( "Kuwait","kw");
        countryMap.put( "Cayman Islands","ky");
        countryMap.put( "Kazakhstan","kz");
        countryMap.put( "Laos","la");
        countryMap.put( "Lebanon","lb");
        countryMap.put( "Saint Lucia","lc");
        countryMap.put( "Liechtenstein","li");
        countryMap.put( "Sri Lanka","lk");
        countryMap.put( "Liberia","lr");
        countryMap.put( "Lesotho","ls");
        countryMap.put( "Lithuania","lt");
        countryMap.put( "Luxembourg","lu");
        countryMap.put( "Latvia","lv");
        countryMap.put( "Libya","ly");
        countryMap.put( "Morocco","ma");
        countryMap.put( "Monaco","mc");
        countryMap.put( "Moldova","md");
        countryMap.put( "Montenegro","me");
        countryMap.put( "Saint Martin","mf");
        countryMap.put( "Madagascar","mg");
        countryMap.put( "Marshall Islands","mh");
        countryMap.put( "North Macedonia","mk");
        countryMap.put( "Mali","ml");
        countryMap.put( "Myanmar","mm");
        countryMap.put( "Mongolia","mn");
        countryMap.put( "Macau","mo");
        countryMap.put( "Northern Mariana Islands","mp");
        countryMap.put( "Martinique","mq");
        countryMap.put( "Mauritania","mr");
        countryMap.put( "Montserrat","ms");
        countryMap.put( "Malta","mt");
        countryMap.put( "Mauritius","mu");
        countryMap.put( "Maldives","mv");
        countryMap.put( "Malawi","mw");
        countryMap.put( "Mexico","mx");
        countryMap.put( "Malaysia","my");
        countryMap.put( "Mozambique","mz");
        countryMap.put( "Madeira","pt");
        countryMap.put( "Namibia","na");
        countryMap.put( "New Caledonia","nc");
        countryMap.put( "Niger","ne");
        countryMap.put( "Norfolk Island","nf");
        countryMap.put( "Nigeria","ng");
        countryMap.put( "Nicaragua","ni");
        countryMap.put( "Netherlands","nl");
        countryMap.put( "Norway","no");
        countryMap.put( "Norway (Nis)","no");
        countryMap.put( "Nepal","np");
        countryMap.put( "Nauru","nr");
        countryMap.put( "Niue","nu");
        countryMap.put( "New Zealand","nz");
        countryMap.put( "Oman","om");
        countryMap.put( "Panama","pa");
        countryMap.put( "Peru","pe");
        countryMap.put( "French Polynesia","pf");
        countryMap.put( "Papua New Guinea","pg");
        countryMap.put( "Philippines","ph");
        countryMap.put( "Pakistan","pk");
        countryMap.put( "Poland","pl");
        countryMap.put( "Saint Pierre and Miquelon","pm");
        countryMap.put( "Pitcairn Islands","pn");
        countryMap.put( "Puerto Rico","pr");
        countryMap.put( "Palestine","ps");
        countryMap.put( "Portugal","pt");
        countryMap.put( "Palau","pw");
        countryMap.put( "Paraguay","py");
        countryMap.put( "Qatar","qa");
        countryMap.put( "Réunion","re");
        countryMap.put( "Romania","ro");
        countryMap.put( "Serbia","rs");
        countryMap.put( "Russia","ru");
        countryMap.put( "Rwanda","rw");
        countryMap.put( "Saudi Arabia","sa");
        countryMap.put( "Solomon Islands","sb");
        countryMap.put( "Seychelles","sc");
        countryMap.put( "Sudan","sd");
        countryMap.put( "Sweden","se");
        countryMap.put( "Singapore","sg");
        countryMap.put( "Saint Helena Ascension and Tristan da Cunha","sh");
        countryMap.put( "Slovenia","si");
        countryMap.put( "Svalbard and Jan Mayen","sj");
        countryMap.put( "Slovakia","sk");
        countryMap.put( "Sierra Leone","sl");
        countryMap.put( "San Marino","sm");
        countryMap.put( "Senegal","sn");
        countryMap.put( "Somalia","so");
        countryMap.put( "Suriname","sr");
        countryMap.put( "South Sudan","ss");
        countryMap.put( "São Tomé and Príncipe","st");
        countryMap.put( "El Salvador","sv");
        countryMap.put( "Sint Maarten","sx");
        countryMap.put( "Syria","sy");
        countryMap.put( "Eswatini (Swaziland)","sz");
        countryMap.put( "Turks and Caicos Islands","tc");
        countryMap.put( "Chad","td");
        countryMap.put( "French Southern and Antarctic Lands","tf");
        countryMap.put( "Togo","tg");
        countryMap.put( "Thailand","th");
        countryMap.put( "Tajikistan","tj");
        countryMap.put( "Tokelau","tk");
        countryMap.put( "Timor-Leste","tl");
        countryMap.put( "Turkmenistan","tm");
        countryMap.put( "Tunisia","tn");
        countryMap.put( "Tonga","to");
        countryMap.put( "Turkey","tr");
        countryMap.put( "Trinidad and Tobago","tt");
        countryMap.put( "Tuvalu","tv");
        countryMap.put( "Taiwan","tw");
        countryMap.put( "Tanzania","tz");
        countryMap.put( "Ukraine","ua");
        countryMap.put( "Uganda","ug");
        countryMap.put( "United States Minor Outlying Islands","um");
        countryMap.put( "United Nations","un");
        countryMap.put( "United States","us");
        countryMap.put( "United States of America","us");
        countryMap.put( "Alaska","us-ak");
        countryMap.put( "Alabama","us-al");
        countryMap.put( "Arkansas","us-ar");
        countryMap.put( "Arizona","us-az");
        countryMap.put( "California","us-ca");
        countryMap.put( "Colorado","us-co");
        countryMap.put( "Connecticut","us-ct");
        countryMap.put( "Delaware","us-de");
        countryMap.put( "Florida","us-fl");
        countryMap.put( "Georgia","us-ga");
        countryMap.put( "Hawaii","us-hi");
        countryMap.put( "Iowa","us-ia");
        countryMap.put( "Idaho","us-id");
        countryMap.put( "Illinois","us-il");
        countryMap.put( "Indiana","us-in");
        countryMap.put( "Kansas","us-ks");
        countryMap.put( "Kentucky","us-ky");
        countryMap.put( "Louisiana","us-la");
        countryMap.put( "Massachusetts","us-ma");
        countryMap.put( "Maryland","us-md");
        countryMap.put( "Maine","us-me");
        countryMap.put( "Michigan","us-mi");
        countryMap.put( "Minnesota","us-mn");
        countryMap.put( "Missouri","us-mo");
        countryMap.put( "Mississippi","us-ms");
        countryMap.put( "Montana","us-mt");
        countryMap.put( "North Carolina","us-nc");
        countryMap.put( "North Dakota","us-nd");
        countryMap.put( "Nebraska","us-ne");
        countryMap.put( "New Hampshire","us-nh");
        countryMap.put( "New Jersey","us-nj");
        countryMap.put( "New Mexico","us-nm");
        countryMap.put( "Nevada","us-nv");
        countryMap.put( "New York","us-ny");
        countryMap.put( "Ohio","us-oh");
        countryMap.put( "Oklahoma","us-ok");
        countryMap.put( "Oregon","us-or");
        countryMap.put( "Pennsylvania","us-pa");
        countryMap.put( "Rhode Island","us-ri");
        countryMap.put( "South Carolina","us-sc");
        countryMap.put( "South Dakota","us-sd");
        countryMap.put( "Tennessee","us-tn");
        countryMap.put( "Texas","us-tx");
        countryMap.put( "Utah","us-ut");
        countryMap.put( "Virginia","us-va");
        countryMap.put( "Vermont","us-vt");
        countryMap.put( "Washington","us-wa");
        countryMap.put( "Wisconsin","us-wi");
        countryMap.put( "West Virginia","us-wv");
        countryMap.put( "Wyoming","us-wy");
        countryMap.put( "Uruguay","uy");
        countryMap.put( "Uzbekistan","uz");
        countryMap.put( "Vatican City (Holy See)","va");
        countryMap.put( "Saint Vincent and the Grenadines","vc");
        countryMap.put( "St Vincent & The Grenadines","vc");
        countryMap.put( "Venezuela","ve");
        countryMap.put( "British Virgin Islands","vg");
        countryMap.put( "United States Virgin Islands","vi");
        countryMap.put( "Vietnam","vn");
        countryMap.put( "Vanuatu","vu");
        countryMap.put( "Wallis and Futuna","wf");
        countryMap.put( "Samoa","ws");
        countryMap.put( "Kosovo","xk");
        countryMap.put( "Yemen","ye");
        countryMap.put( "Mayotte","yt");
        countryMap.put( "South Africa","za");
        countryMap.put( "Zambia","zm");
        countryMap.put( "Zimbabwe","zw");
    }

    public String getCountryCode(String countryName){

        return countryMap.get(countryName);
    }

}
